# Generated by Django 4.1.1 on 2022-09-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('prof', models.TextField(max_length=50, null=True)),
                ('code', models.CharField(max_length=6)),
                ('offering', models.CharField(max_length=20)),
                ('review', models.TextField(max_length=300, null=True)),
                ('median_grade', models.FloatField(null=True)),
                ('variance', models.FloatField(null=True)),
                ('workload', models.FloatField(null=True)),
                ('teaching', models.FloatField(null=True)),
            ],
            options={
                'unique_together': {('code', 'offering')},
            },
        ),
    ]
