# Generated by Django 4.1.1 on 2022-09-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade_card',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
